// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-3KHdG1D5qYZgmZClhnUu1xk1YiM1d0A',
    appId: '1:533611049948:web:294e4ed30fd95b809a1519',
    messagingSenderId: '533611049948',
    projectId: 'eventsn-cd5a9',
    authDomain: 'eventsn-cd5a9.firebaseapp.com',
    storageBucket: 'eventsn-cd5a9.firebasestorage.app',
    measurementId: 'G-1WBG088L4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7K5QuCARDJtbhYmrkWH6X28xKvEtWVUE',
    appId: '1:533611049948:android:28149396ca74f3759a1519',
    messagingSenderId: '533611049948',
    projectId: 'eventsn-cd5a9',
    storageBucket: 'eventsn-cd5a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByt1MzuQaBVc-p3TxnaZDDGcBwBvNTyqk',
    appId: '1:533611049948:ios:525b24fd0f726cbb9a1519',
    messagingSenderId: '533611049948',
    projectId: 'eventsn-cd5a9',
    storageBucket: 'eventsn-cd5a9.firebasestorage.app',
    iosBundleId: 'com.example.eventSn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByt1MzuQaBVc-p3TxnaZDDGcBwBvNTyqk',
    appId: '1:533611049948:ios:525b24fd0f726cbb9a1519',
    messagingSenderId: '533611049948',
    projectId: 'eventsn-cd5a9',
    storageBucket: 'eventsn-cd5a9.firebasestorage.app',
    iosBundleId: 'com.example.eventSn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-3KHdG1D5qYZgmZClhnUu1xk1YiM1d0A',
    appId: '1:533611049948:web:83d2c35b1e4687809a1519',
    messagingSenderId: '533611049948',
    projectId: 'eventsn-cd5a9',
    authDomain: 'eventsn-cd5a9.firebaseapp.com',
    storageBucket: 'eventsn-cd5a9.firebasestorage.app',
    measurementId: 'G-RDLVX8GE46',
  );

}